### ISSUE TITLE
HTTP/2 internal error while retrieving large amounts of data from Ubergraph

### ISSUE THREAD

**Issue by gaurav** [INCATools/ubergraph#47]
I'm running into an HTTP/2 error [`curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)`] after downloading data for about 30 seconds when making [a large query](https://gist.github.com/gaurav/a3a51d2e8b0b8c6e75069b140db5284f#request-from-babel.sparql) from Ubergraph. I think it might be caused by a java.util.concurrent.TimeoutException at around the 30 second mark.

## Steps to reproduce:
1. `curl "https://gist.githubusercontent.com/gaurav/a3a51d2e8b0b8c6e75069b140db5284f/raw/98f037ce61859ce8923c2e05b218efac4d3b83c2/request-from-babel.sparql" > request.sparql`
2. `curl -v -X POST "https://ubergraph.apps.renci.org/sparql" -H "Content-Type: application/sparql-query" --data-binary "@request.sparql" --output result.xml`

## Expected outcome
1. Request completes and produces valid XML.

## Actual output:
<details><summary>Request</summary>

```
Note: Unnecessary use of -X or --request, POST is already inferred.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 152.54.15.132:443...
* Connected to ubergraph.apps.renci.org (152.54.15.132) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [238 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [102 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [4040 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [300 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [37 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=ubergraph.apps.renci.org
*  start date: Feb  1 17:32:50 2022 GMT
*  expire date: May  2 17:32:49 2022 GMT
*  subjectAltName: host "ubergraph.apps.renci.org" matched cert's "ubergraph.apps.renci.org"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f900300b600)
> POST /sparql HTTP/2
> Host: ubergraph.apps.renci.org
> user-agent: curl/7.77.0
> accept: */*
> content-type: application/sparql-query
> content-length: 399
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
} [399 bytes data]
* We are completely uploaded and fine
```
</details>

```
< HTTP/2 200 
< date: Tue, 01 Mar 2022 21:08:52 GMT
< content-type: application/sparql-results+xml;charset=utf-8
< x-frame-options: SAMEORIGIN
< strict-transport-security: max-age=15724800; includeSubDomains
< access-control-allow-origin: *
< access-control-allow-credentials: true
< 
{ [3899 bytes data]
100  409M    0  409M  100   399  13.4M     13  0:00:30  0:00:30 --:--:-- 13.4M* HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
* stopped the pause stream!
100  412M    0  412M  100   399  13.4M     12  0:00:33  0:00:30  0:00:03 13.7M
* Connection #0 to host ubergraph.apps.renci.org left intact
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
```

The generated XML file is interrupted.
```shell
$ tail result.xml
			<binding name='cls'>
				<uri>http://purl.obolibrary.org/obo/NCIT_C60825</uri>
			</binding>
			<binding name='pred'>
				<uri>http://www.geneontology.org/formats/oboInOwl#hasExactSynonym</uri>
			</binding>
			<binding name='val'>
				<literal datatype='http://www.w3.org/2001/XMLSchema#string'>Lipase Hypersecretion Syndrome</literal>
			</binding>
		</r%
```

## Possible cause: java.util.concurrent.TimeoutException

On one invocation, I weirdly got ~416M of results, followed by part of the SPARQL query, followed by a java.util.concurrent.TimeoutException:

```
$ tail -n1000 result.xml
[...]
		<result>
			<binding name='cls'>
				<uri>http://purl.obolibrary.org/obo/NCIT_C52504</uri>
			</binding>
			<binding name='pred'>
				<uri>http://www.geneontology.org/formats/oboInOwl#hasExactSynonym</uri>SPARQL-QUERY: queryStr=prefix owl: <http://www.w3.org/2002/07/owl#>
prefix oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>

SELECT ?cls ?pred ?val
from <http://reasoner.renci.org/ontology>
WHERE
{ ?cls ?pred ?val ;
       a owl:Class .
  FILTER (
    ?pred = oboInOwl:hasRelatedSynonym ||
    ?pred = oboInOwl:hasNarrowSynonym ||
    ?pred = oboInOwl:hasBroadSynonym ||
    ?pred = oboInOwl:hasExactSynonym
  )
}
java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at com.bigdata.rdf.sail.webapp.BigdataServlet.submitApiTask(BigdataServlet.java:292)
	at com.bigdata.rdf.sail.webapp.QueryServlet.doSparqlQuery(QueryServlet.java:678)
	at com.bigdata.rdf.sail.webapp.QueryServlet.doPost(QueryServlet.java:275)
	at com.bigdata.rdf.sail.webapp.RESTServlet.doPost(RESTServlet.java:269)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:248)
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:211)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by balhoff** [comment]
For this query it's probably better to use `VALUES`:

```sparql
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>

SELECT DISTINCT ?cls ?pred ?val
from <http://reasoner.renci.org/ontology>
WHERE
{ 
  VALUES ?pred { oboInOwl:hasRelatedSynonym oboInOwl:hasNarrowSynonym oboInOwl:hasBroadSynonym oboInOwl:hasExactSynonym }
  ?cls ?pred ?val ;
       a owl:Class .
}
```

But this version still times out; it's a really large result. I will look into increasing the timeout.

**Comment by balhoff** [comment]
@gaurav I increased the timeout to 60 seconds. Can you try the `VALUES` version now?

**Comment by gaurav** [comment]
That looks like it works -- this query completes in around 40 seconds now.

**Comment by gaurav** [comment]
Seems to be working on Sterling as well, so I'll close this for now. Thanks, Jim!
